### ISSUE TITLE
SMVTrain error!

### ISSUE THREAD

**Issue by BoyuanJiang** [yaohungt/Cross-Domain-Landmarks-Selection-CDLS-#1]
In SVM_test.m has the following code:
`model = svmtrain(pivot_weight,pivot_label,sparse(pivot_feature),'-s 1 -t 0 -q');`

however,My svmtrain function only accept three parameters **training_label_vector, training_instance_matrix, 'libsvm_options'**,see [this](https://github.com/cjlin1/libsvm/blob/v320/matlab/svmtrain.c#L25)
So why in your code have **pivot_weight** parameter

**Comment by yaohungt** [comment]
I think this is because of different versions of SVM. I faced this issue once, and later I updated the package; everything worked fine.
